name: Quality checks

on:
  push:
  pull_request:

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node (for linkinator)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install linkinator
        run: npm i -g linkinator
      - name: HTML link check
        run: |
          linkinator "index.html" "about.html" "services.html" "projects.html" "certifications.html" "contacts.html" \
            --recurse --skip "https://engin-by.netlify.app/admin/,/admin/" --verbosity error

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: frenck/action-yamllint@v1
        with:
          config_file: .yamllint.yaml

